#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': '',
 'author_email': '',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': '',
 'download_url': '',
 'entry_points': '[openmdao.caseiterator]\nplotcase.plotcase.PlotCaseIterator=plotcase.plotcase:PlotCaseIterator\n\n[openmdao.caserecorder]\nplotcase.plotcase.PlotCaseRecorder=plotcase.plotcase:PlotCaseRecorder',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': '',
 'maintainer': '',
 'maintainer_email': '',
 'name': 'plotcase',
 'package_data': {'plotcase': ['test\\test_plotcase.py']},
 'package_dir': {'': 'src'},
 'packages': ['plotcase'],
 'url': '',
 'version': '0.1.0',
 'zip_safe': False}


setup(**kwargs)

